name: "\U0001F4D6 Documentation Feedback"
description: "Report an issue with the documentation or suggest an improvement."
title: "[\U0001F4DA] Documentation Issue Title - CHANGE ME "
labels: ["help wanted"]
assignees: []
body:
  - type: textarea
    id: feedback
    attributes:
      label: Documentation Feedback
      description: Please describe your documentation issue or suggested improvement in detail here and provide links to any pre-existing/relevant documentation and screenshots if necessary.
      placeholder: Give us your detailed feedback!
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
        👉 Check out [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.
